### ISSUE TITLE
Application Development Path

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/bcp-demo#15]
This is another path of related tasks that one person can work on that build upon each other:

- [ ] Code Review of BCP Demo / Atomic Swap #8 
- [ ] Update Extension writing docs https://github.com/confio/weave/issues/57
- [ ] Review BCP spec
- [ ] Add NFT support
- [ ] Update Extension writing docs https://github.com/confio/weave/issues/57
- [ ] Review BNS spec
- [ ] Implement name spaces
- [ ] Implement blockchain registration
